@startuml

actor OW as "Organization Worker"

rectangle Database

rectangle "Organization System" {
    usecase UC2 as "Get all counties in a continent
    organised by largest to smallest"

    OW - UC2
    UC2 - Database
}

@enduml