@startuml

actor OW as "Organization Worker"

rectangle Database

rectangle "Organization System" {
    usecase UC1c as "Get all counties in a region
    organised by largest to smallest"

    OW - UC1c
    UC1c - Database
}

@enduml