@startuml

actor OW as "Organization Worker"

rectangle Database

rectangle "Organization System" {
    usecase UC1a as "Get all counties in the world
    organised by largest to smallest"

    OW - UC1a
    UC1a - Database
}

@enduml