@startuml

actor OW as "Organization Worker"

rectangle Database

rectangle "Organization System" {
    usecase UC1b as "Get all counties in a continent
    organised by largest to smallest"

    OW - UC1b
    UC1b - Database
}

@enduml