@startuml
left to right direction

actor OW as "Organization Worker"

rectangle Database

rectangle "Organization System" {

    usecase UC1 as "Get all countries organised
    by largest population to smallest"

    usecase UC2 as "Get Top N Populated Capital
    Cities where N is Provided by the User"

    usecase UC3 as "Get all capital cities organised
    by largest population to smallest"

    usecase UC4 as "Get all the Population of People,
    People Living in Cities, and People not
    Living in Cities"

    usecase UC5 as "Get all the Cities organised
    by largest population to smallest"

    usecase UC6 as "Get the Top N Populated Countries
    where N is Provided by the User"

    usecase UC7 as "Get top N populated cities where
    N is provided by the user"

    usecase UC8 as "Get population"

    usecase UC9 as "Get population languages"

    usecase UCa as "Print report"

        OW -- UC1
        UC1 ..> UCa : include
        UC1 -- Database

        OW -- UC2
        UC2 ..> UCa : include
        UC2 -- Database

        OW -- UC3
        UC3 ..> UCa : include
        UC3 -- Database

        OW -- UC4
        UC4 ..> UCa : include
        UC4 -- Database

        OW -- UC5
        UC5 ..> UCa : include
        UC5 -- Database

        OW -- UC6
        UC6 ..> UCa : include
        UC6 -- Database

        OW -- UC7
        UC7 ..> UCa : include
        UC7 -- Database

        OW -- UC8
        UC8 ..> UCa : include
        UC8 -- Database

        OW -- UC9
        UC9 ..> UCa : include
        UC9 -- Database

}

@enduml